# Pipeline de Atualização — Monitoramento Parlamentar

Este notebook executa o pipeline de ETL completo:
1. Carrega a planilha CGNOR
2. Extrai referências legislativas
3. Enriquece com dados das APIs da Câmara e Senado
4. Normaliza e exporta o CSV final

A lógica de negócio está nos módulos em `src/`. Este notebook apenas orquestra a execução.

In [7]:
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)

In [8]:
from src.pipeline import (
    carregar_planilha,
    extrair_referencias,
    enriquecer_com_apis,
    normalizar_colunas,
)
from src.configuracao import CAMINHO_DADOS, ARQUIVO_PLANILHA, ARQUIVO_CSV_FINAL
import os

## 1. Carregar Planilha

In [9]:
caminho_planilha = os.path.join(CAMINHO_DADOS, ARQUIVO_PLANILHA)
df = carregar_planilha(caminho_planilha)
df.head()

2026-05-21 14:58:53,037 [INFO] src.pipeline: Carregando planilha: data\Levantamento de prazos para análise de PLs.xlsx
2026-05-21 14:58:53,113 [INFO] src.pipeline: Planilha carregada: 68 linhas.

,Nº,Processo,Projeto de LEI,Descrição,Encaminhamento prévio - Teams/E-mail,1º Encaminhamento - Remetente,1º Encaminhamento - Despacho /Ofício,1º Encaminhamento - Data,1º Encaminhamento - Prazo p/ Resposta,2º Encaminhamento - Remetente,...,Período de elaboração da Análise - Quantidade de dias úteis,Envio para a Delog - Data,Envio ao Gabinete da Seges - Data,Validação pelo gabinete da Seges - Quantidade de dias úteis,Assinaturas - Data,Manifestação da Seges - Nota técnica,Andamento do PL - Data/Detalhamento,Observações andamento - Parecer,Integração SEI - Processo,Integração SEI - Anotação do Bloco Interno
0,1,18001.102696/2023-68,PL nº 4603/2023,"""Altera a Lei nº 11.578, de 26 de\nnovembro de...",xxx,Assessoria Especial de Assuntos Parlamentares ...,OFÍCIO SEI Nº 153985/2023/MGI (SEI 39219578),2023-12-20 00:00:00,2024-01-12 00:00:00,Assessoria Estratégica SEGES,...,11,2024-01-10 00:00:00,2024-01-10 00:00:00,8,2024-01-19 00:00:00,contrária ao PL,"Retirado de pauta, de ofício, em virtude da au...",https://www.camara.leg.br/proposicoesWeb/prop_...,<NA>,<NA>
1,2,18001.000215/2024-61,PL 510/2021,"""Altera a Lei n°11.952, de 25 de junho de 2009...",xxx,Assessoria Especial de Assuntos Parlamentares ...,OFÍCIO SEI Nº 9434/2024/MGI (SEI 39790971),2024-01-30 00:00:00,XXX,Assessoria Estratégica SEGES,...,7,2024-02-06 00:00:00,XXX,9,2024-02-20 00:00:00,"Em conclusão, esta unidade técnica, dentro de ...",2ª autuação\n \n22/11/2023\nCMA - Comissão de ...,https://www25.senado.leg.br/web/atividade/mate...,<NA>,<NA>
2,3,18001.000214/2024-17,PLnº2633/2020,"""altera as Leis nºs 11.952, de 25 de junho de ...",xxx,Assessoria Especial de Assuntos Parlamentares ...,OFÍCIO SEI Nº 9377/2024/MGI (SEI 39789102),2024-01-30 00:00:00,XXX,Assessoria Estratégica SEGES,...,9,2024-02-05 00:00:00,XXX,10,2024-02-20 00:00:00,"Em conclusão, esta unidade técnica, dentro de ...",2ª autuação\n \n22/11/2023\nCMA - Comissão de ...,https://www25.senado.leg.br/web/atividade/mate...,<NA>,<NA>
3,4,18001.102523/2023-40,"PL nº 2789, de 2021","""Moderniza a Lei nº 8.159, de 8 de janeiro de ...",xxx,Assessoria Especial de Assuntos Parlamentares ...,OFÍCIO SEI Nº 142672/2023/MGI (SEI 38762676),2024-01-31 00:00:00,XXX,Assessoria Estratégica SEGES,...,9,2024-03-27 00:00:00,2024-03-28 00:00:00,12,2024-04-15 00:00:00,"Diante do exposto, considerando-se as competên...",13/08/2024\nCCULT - Comissão de Cultura\nAção:...,https://www.camara.leg.br/proposicoesWeb/ficha...,<NA>,<NA>
4,5,18001.000372/2024-77,PL - emergência fitossanitária,Dispõe sobre as medidas para o enfrentamento d...,xxx,Assessoria Especial de Assuntos Parlamentares ...,Despacho MGI-GM- ASPAR (SEI 40201222),2024-02-19 00:00:00,xxx,Assessoria Estratégica SEGES (Urgente),...,1,2024-02-19 00:00:00,2024-02-19 00:00:00,1,2024-02-19 00:00:00,NaN,NaN,NaN,<NA>,<NA>

## 2. Extrair Referências Legislativas

In [10]:
df = extrair_referencias(df)
df[["Projeto de LEI", "sigla", "numero", "ano", "Projeto de Lei - Regex"]].head(10)

2026-05-21 14:58:53,133 [INFO] src.pipeline: Extraindo referencias legislativas...
2026-05-21 14:58:53,134 [INFO] src.pipeline: Referencias extraidas: 68/68 com sigla identificada.

,Projeto de LEI,sigla,numero,ano,Projeto de Lei - Regex
0,PL nº 4603/2023,PL,4603,2023,PL 4603/2023
1,PL 510/2021,PL,510,2021,PL 510/2021
2,PLnº2633/2020,PL,2633,2020,PL 2633/2020
3,"PL nº 2789, de 2021",PL,2789,2021,PL 2789/2021
4,PL - emergência fitossanitária,PL,<NA>,<NA>,<NA>
5,PDL nº 4/2024,PDL,4,2024,PDL 4/2024
6,PL nº 1.498/2023,PL,1498,2023,PL 1498/2023
7,PL nº 4363/2011,PL,4363,2011,PL 4363/2011
8,PL - emergência fitossanitária ( Novo texto),PL,<NA>,<NA>,<NA>
9,PL n° 2607/2021,PL,2607,2021,PL 2607/2021

## 3. Enriquecer com APIs (Câmara + Senado)

In [11]:
df = enriquecer_com_apis(df)
df["Origem Dados"].value_counts()

2026-05-21 14:58:53,149 [INFO] src.pipeline: Iniciando enriquecimento bicameral...
2026-05-21 14:58:53,154 [INFO] src.enriquecedor: Enriquecendo 63 referencias unicas...
2026-05-21 14:59:12,482 [INFO] src.enriquecedor: Progresso: 10/63
2026-05-21 14:59:27,265 [INFO] src.enriquecedor: Progresso: 20/63
2026-05-21 14:59:45,190 [INFO] src.enriquecedor: Progresso: 30/63
2026-05-21 15:00:03,471 [INFO] src.enriquecedor: Progresso: 40/63
2026-05-21 15:00:44,501 [INFO] src.enriquecedor: Progresso: 50/63
2026-05-21 15:01:21,401 [INFO] src.enriquecedor: Progresso: 60/63
2026-05-21 15:01:30,134 [INFO] src.enriquecedor: Progresso: 63/63
2026-05-21 15:01:31,850 [INFO] src.enriquecedor: Enriquecimento concluido: 63 referencias processadas.
2026-05-21 15:01:31,864 [INFO] src.pipeline: Merge concluido: 68 linhas no resultado final.

Origem Dados
Câmara             37
Câmara + Senado    17
Senado              8
Não encontrado      4
Name: count, dtype: int64

## 4. Normalizar e Exportar

In [12]:
df = normalizar_colunas(df)

caminho_csv = os.path.join(CAMINHO_DADOS, ARQUIVO_CSV_FINAL)
df.to_csv(caminho_csv, index=False, encoding="utf-8-sig")

print(f"CSV exportado: {caminho_csv} ({len(df)} linhas)")
df.head()

2026-05-21 15:01:31,883 [INFO] src.pipeline: Normalizando colunas...

CSV exportado: data\df_final_bicameral.csv (68 linhas)

,Projeto de LEI,Projeto de Lei - Regex,sigla,numero,ano,Origem Dados,camara_id_proposicao,camara_projeto,camara_ementa,camara_data_proposta_pl,...,Período de elaboração da Análise - Quantidade de dias úteis,Envio para a Delog - Data,Envio ao Gabinete da Seges - Data,Validação pelo gabinete da Seges - Quantidade de dias úteis,Assinaturas - Data,Manifestação da Seges - Nota técnica,Andamento do PL - Data/Detalhamento,Observações andamento - Parecer,Integração SEI - Processo,Integração SEI - Anotação do Bloco Interno
0,PL nº 4603/2023,PL 4603/2023,PL,4603,2023,Câmara,2389587,PL 4603/2023,"Altera a Lei nº 11.578, de 26 de novembro de 2...",20/09/2023,...,11,10/01/2024,10/01/2024,8,19/01/2024,contrária ao PL,"Retirado de pauta, de ofício, em virtude da au...",https://www.camara.leg.br/proposicoesWeb/prop_...,<NA>,<NA>
1,PL 510/2021,PL 510/2021,PL,510,2021,Senado,<NA>,NaN,NaN,,...,7,06/02/2024,,9,20/02/2024,"Em conclusão, esta unidade técnica, dentro de ...",2ª autuação\n \n22/11/2023\nCMA - Comissão de ...,https://www25.senado.leg.br/web/atividade/mate...,<NA>,<NA>
2,PLnº2633/2020,PL 2633/2020,PL,2633,2020,Câmara + Senado,2252589,PL 2633/2020,"Altera a Lei n° 11.952, de 25 de junho de 2009...",14/05/2020,...,9,05/02/2024,,10,20/02/2024,"Em conclusão, esta unidade técnica, dentro de ...",2ª autuação\n \n22/11/2023\nCMA - Comissão de ...,https://www25.senado.leg.br/web/atividade/mate...,<NA>,<NA>
3,"PL nº 2789, de 2021",PL 2789/2021,PL,2789,2021,Câmara,2293801,PL 2789/2021,"Moderniza a Lei nº 8.159, de 8 de janeiro de 1...",11/08/2021,...,9,27/03/2024,28/03/2024,12,15/04/2024,"Diante do exposto, considerando-se as competên...",13/08/2024\nCCULT - Comissão de Cultura\nAção:...,https://www.camara.leg.br/proposicoesWeb/ficha...,<NA>,<NA>
4,PL - emergência fitossanitária,<NA>,PL,<NA>,<NA>,NaN,<NA>,NaN,NaN,,...,1,19/02/2024,19/02/2024,1,19/02/2024,NaN,NaN,NaN,<NA>,<NA>